spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.50.184.138:3307/zyh_dev_EasyApplyResume?useSSL=false&serverTimezone=UTC
    username: root
    password: root
ali:

  bailian:
    api-key: "sk-199ed9d5c8214c0eadcf179d4062fc00"