spring:
  ai:
    mcp:
      server:
        name: image-search-mcp-server
        version: 0.0.1
        type: SYNC
        # stdio
        stdio: false
  mvc:
    async:
      request-timeout: 300000  # 5分钟（毫秒）
  server:
    tomcat:
      connection-timeout: 300000  # Tomcat 连接超时 5 分钟
      keep-alive-timeout: 300000  # Keep-Alive 超时
